export const INGREDIENT_CONSTRUCTOR_ADD: "INGREDIENT_CONSTRUCTOR_ADD" =
  "INGREDIENT_CONSTRUCTOR_ADD";
export const INGREDIENT_CONSTRUCTOR_DELETE: "INGREDIENT_CONSTRUCTOR_DELETE" =
  "INGREDIENT_CONSTRUCTOR_DELETE";
export const INGREDIENT_CONSTRUCTOR_REORDER: "INGREDIENT_CONSTRUCTOR_REORDER" =
  "INGREDIENT_CONSTRUCTOR_REORDER";
export const INGREDIENT_CONSTRUCTOR_RESET: "INGREDIENT_CONSTRUCTOR_RESET" =
  "INGREDIENT_CONSTRUCTOR_RESET";
