export const ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST" =
  "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS" =
  "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_ERROR: "ORDER_DETAILS_ERROR" = "ORDER_DETAILS_ERROR";
export const ORDER_DETAILS_CLOSE: "ORDER_DETAILS_CLOSE" = "ORDER_DETAILS_CLOSE";
